target-version = "py312"
line-length = 88
indent-width = 4

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

[lint]
select = [
    "F",
    "E",
    "W",
    "C90",
    "I",
    "N",
    "UP",
    "YTT",
    # "ANN", # flake8-annotations: we should support this in the future but 100+ errors atm
    "ASYNC",
    "S",
    "BLE",
    "FBT",
    "B",
    "A",
    "COM",
    "C4",
    "DTZ",
    "T10",
    "DJ",
    "EM",
    "EXE",
    "FA",
    'ISC',
    "ICN",
    "G",
    'INP',
    'PIE',
    "T20",
    'PYI',
    'PT',
    "Q",
    "RSE",
    "RET",
    "SLF",
    "SLOT",
    "SIM",
    "TID",
    "TCH",
    "INT",
    # "ARG", # Unused function argument
    "PTH",
    "ERA",
    "PD",
    "PGH",
    "PL",
    "TRY",
    "FLY",
    # "NPY",
    # "AIR",
    "PERF",
    # "FURB",
    # "LOG",
    "RUF",
]
ignore = [
    "UP006",
    "UP038",
    "SIM118",
    "FBT001",
    "FBT002",
    "UP035",
    "G004",
    "RET504",
    "UP007",
    "S101",    # Use of assert detected https://docs.astral.sh/ruff/rules/assert/
    "RUF012",  # Mutable class attributes should be annotated with `typing.ClassVar`
    "SIM102",  # sometimes it's better to nest
    "COM812",  # missing-trailing-comma recommended to remove
    "ISC001",  # single-line-implicit-string-concatenation recommended to remove
    "E501",    # line too long
    "PD901",   # generic names
    "ERA001",  # commented out code
    "PT009",   # regular assert instead of unittest style
    "N801",    # name with caps
    "N806",
    "UP017",   # Dont change my timezone
    "PTH118",  # `os.path.join()` should be replaced by `Path` with `/` operator
    "TRY003",
    "T201",
    "T203",
    "EM102",
    "PLR2004",
    "PTH123",
    "C408",
    "PLR0913",
    "EM101",
    "TID252",
    "PLR2004",
    "PT027",
    "FBT003",
    "S603",
    "INP001",
    "PTH207",
]
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
